# Default DataEditingConfig (Hydra/OmegaConf)

run:
  id: null
  dataset_key: null
  user: null

data:
  dataset_id: null
  csv_path: "data/example.csv"
  target_column: null
  feature_columns: null
  problem_type: null
  test_size: 0.0
  random_seed: 42

editing:
  enable: false
  output_path: null
  output_dir: null
  output_filename: "edited.csv"
  drop_columns: []
  rename_columns: {}
  fillna: null
  fillna_columns: {}
  query: null
  clip_values: {}

clearml:
  enabled: true
  project_name: "AutoML-with-ClearML"
  dataset_project: "AutoML-datasets"
  base_output_uri: null
  queue: "default"
  tags: ["automl", "data_editing"]
  enable_data_editing: true
  run_tasks_locally: true

